TABLES_TO_MONITOR = [
    #CHOCOSUL.PCROTAEXP",
    "CHOCOSUL.PCVEICUL",
    "CHOCOSUL.PCEMPR",
    "CHOCOSUL.PCFORNEC"
    #"CHOCOSUL.PCMANIFESTOELETRONICOC"
]

QUERIES_TO_MONITOR = [
    #SELECT CODROTA FROM CHOCOSUL.PCROTAEXP",
    "SELECT CODVEICULO FROM CHOCOSUL.PCVEICUL",
    "SELECT MATRICULA FROM CHOCOSUL.PCEMPR",
    "SELECT CODFORNEC FROM CHOCOSUL.PCFORNEC"
    #"SELECT NUMTRANSACAO FROM CHOCOSUL.PCMANIFESTOELETRONICOC",
]

# TODO: CRIAR DICIONARIO COM TABLE, COLUMN_ID, OU JÁ PASSAR AS QUERYS DAQUI MESMO.