SELECT DISTINCT
    C.NUMCAR
    ,t2.ORIGEM
    ,C.DESTINO
    ,CASE 
        WHEN (COUNT(m.DTINICIOOS) >= 1 AND COUNT(m.DTFIMOS) < COUNT(1)) AND COUNT(1) > 0 
        THEN 'S' 
        ELSE 'N' 
    END AS EM_SEPARACAO
    ,CASE 
        WHEN (COUNT(m.DTFIMSEPARACAO) = COUNT(1) OR COUNT(m.DTFIMOS) = COUNT(1)) AND COUNT(1) > 0 
        THEN 'S' 
        ELSE 'N' 
    END AS SEPARADO
    ,CASE 
        WHEN (COUNT(m.DTINICIOCONFERENCIA) >= 1 AND COUNT(m.DTFIMOS) < COUNT(1)) AND COUNT(1) > 0 
        THEN 'S' 
        ELSE 'N' 
    END AS EM_CONFERENCIA
    ,CASE 
        WHEN (COUNT(m.DTFIMCONFERENCIA) = COUNT(1)OR COUNT(m.DTFIMOS) = COUNT(1)) AND COUNT(1) > 0 
        THEN 'S' 
        ELSE 'N' 
    END AS CONFERIDO
    ,c.DTSAIDA
    ,c.DATAMON
    ,c.HORAMON
    ,c.MINUTOMON
    ,c.DTFECHA
    ,c.CODMOTORISTA
    ,e1.NOME AS MOTORISTA
    ,c.CODVEICULO
    ,c.TOTPESO
    ,c.TOTVOLUME
    ,c.VLTOTAL
    ,c.CODROTAPRINC
    ,r.CODROTA
    ,r.DESCRICAO AS ROTA
    ,c.NUMNOTAS
    ,c.QTITENS
    ,c.OBSFATUR
    ,c.TIPOCARGA
    ,c.OBSDESTINO
    ,c.CARGASECUNDARIA
    ,r.SITUACAO
    ,r.KMROTA
    ,r.VLMINCARREG
    ,r.PRAZOPREVENT
    ,r.TIPOCOMISSAO
    ,r.VLDIARIA
    ,r.NUMDIARIA
    ,r.RASTREADA
    ,r.DIASENTREGA
    ,COALESCE(MAX(m.NUMPALETE), 0) AS QT_PALETES
    ,COUNT(DISTINCT p.CODCLI) AS QT_ENTREGAS
    ,LISTAGG(DISTINCT m.TIPOOS, ', ') AS TIPOOS_LIST
FROM CHOCOSUL.PCCARREG c
    INNER JOIN CHOCOSUL.PCROTAEXP r   ON r.CODROTA = c.CODROTAPRINC
    INNER JOIN CHOCOSUL.PCPEDC p      ON p.NUMCAR = c.NUMCAR
    LEFT JOIN CHOCOSUL.PCEMPR e1      ON c.CODMOTORISTA = e1.MATRICULA
    LEFT JOIN CHOCOSUL.PCMOVENDPEND m ON c.NUMCAR = m.NUMCAR
    LEFT JOIN CHOCOSUL.PCTIPOOS o     ON m.TIPOOS = o.CODIGO
    INNER JOIN (
        SELECT DISTINCT
            c.NUMCAR
            ,CASE 
            WHEN p.CODFILIAL IN (1, 2)    THEN 'EUNÁPOLIS' 
            WHEN p.CODFILIAL IN (12, 13)  THEN 'ITABUNA'
            ELSE 'OUTRA'
            END AS ORIGEM
        FROM CHOCOSUL.PCCARREG c
            INNER JOIN CHOCOSUL.PCPEDC p        ON p.NUMCAR = c.NUMCAR
            LEFT JOIN CHOCOSUL.PCMOVENDPEND m   ON c.NUMCAR = m.NUMCAR
        WHERE 1=1
            AND C.NUMCAR LIKE NVL(:NUMCAR, C.NUMCAR)
            AND NVL(c.DATAMON, c.DTSAIDA) >= TRUNC(SYSDATE) - NVL(:NUM_DIAS, 0)
            AND m.DTESTORNO IS NULL
        GROUP BY c.NUMCAR, p.CODFILIAL
    ) t2 ON t2.NUMCAR = C.NUMCAR
WHERE 1=1
    -- AND C.NUMCAR LIKE NVL(:NUMCAR, C.NUMCAR)
    -- AND NVL(C.DATAMON, C.DTSAIDA) >= TRUNC(SYSDATE) - NVL(:NUM_DIAS, 7)
    -- AND m.DTESTORNO IS NULL
GROUP BY 
    C.NUMCAR
    ,t2.ORIGEM
    ,c.DTSAIDA
    ,c.DATAMON
    ,c.HORAMON
    ,c.MINUTOMON
    ,c.DESTINO
    ,c.DTFECHA
    ,c.CODMOTORISTA
    ,e1.NOME
    ,c.CODVEICULO
    ,c.TOTPESO
    ,c.TOTVOLUME
    ,c.VLTOTAL
    ,c.CODROTAPRINC
    ,r.CODROTA
    ,r.DESCRICAO
    ,c.NUMNOTAS
    ,c.QTITENS
    ,c.OBSFATUR
    ,c.TIPOCARGA
    ,c.OBSDESTINO
    ,c.CARGASECUNDARIA
    ,r.SITUACAO
    ,r.KMROTA
    ,r.VLMINCARREG
    ,r.PRAZOPREVENT
    ,r.TIPOCOMISSAO
    ,r.VLDIARIA
    ,r.NUMDIARIA
    ,r.RASTREADA
    ,r.DIASENTREGA
ORDER BY c.NUMCAR