/*
    A partir da rotina 982 - Cadastro de Figura de Frete
*/

-- Transporte
SELECT
	  PCTRANSPORTE.CODTRANSPORTE
	, PCTRANSPORTE.CODTRANSPORTADORA
	, PCFORNEC.FORNECEDOR TRANSPORTADORA
	, PCTRANSPORTE.DTVIGENCIAINICIO
	, PCTRANSPORTE.DTVIGENCIAFINAL
	, PCTRANSPORTEPRACA.CODPRACAORIGEM
	, PCPRACAORIGEM.PRACA AS NOME_PRACA_ORIGEM
	, PCTRANSPORTEPRACA.CODPRACADESTINO
	, PCPRACADESTINO.PRACA AS NOME_PRACA_DESTINO
	, PCTIPOVEICULO.CODTIPOVEICULO
	, PCTIPOVEICULO.DSCTIPOVEICULO
	, PCTRANSPORTEPRACA.VLINICIO
	, PCTRANSPORTEPRACA.VLFINAL
FROM 
	PCTRANSPORTE 
    -- Transportadora
	INNER JOIN PCFORNEC ON ( 
		( 
			( 
				(
					PCTRANSPORTE.CODTRANSPORTADORA = PCFORNEC.CODFORNEC AND 
					PCTRANSPORTE.DTEXCLUSAO IS NULL 
				)
            	AND ( PCTRANSPORTE.CODTRANSPORTE = NVL(:CODTRANSPORTE, PCTRANSPORTE.CODTRANSPORTE) ) 
			)
        	AND ( PCTRANSPORTE.CODTRANSPORTADORA = NVL(:CODTRANSPORTADORA, PCTRANSPORTE.CODTRANSPORTADORA) ) 
		)
        AND PCTRANSPORTE.TIPOTRANSPORTE = NVL(:TIPOTRANSPORTE, PCTRANSPORTE.TIPOTRANSPORTE)
	)
	-- Contrato - Origem/Destino/Valor
	INNER JOIN PCTRANSPORTEPRACA ON PCTRANSPORTEPRACA.CODTRANSPORTE = PCTRANSPORTE.CODTRANSPORTE AND 
	( 
		PCTRANSPORTEPRACA.CODTIPOVEICULO = NVL(:CODTIPOVEICULO, PCTRANSPORTEPRACA.CODTIPOVEICULO) 
	) 
	-- Praça de Origem
	INNER JOIN PCPRACA PCPRACAORIGEM  ON PCTRANSPORTEPRACA.CODPRACAORIGEM  = PCPRACAORIGEM.CODPRACA
	-- Praça de Destino
	INNER JOIN PCPRACA PCPRACADESTINO ON PCTRANSPORTEPRACA.CODPRACADESTINO = PCPRACADESTINO.CODPRACA
	-- Tipo Veículo
	INNER JOIN PCTIPOVEICULO ON PCTRANSPORTEPRACA.CODTIPOVEICULO = PCTIPOVEICULO.CODTIPOVEICULO
