WITH dados_completos AS (
    SELECT 
        R.CODROTA,
        P.CEPFINAL,
        P.CEPINICIAL,
        P.DISTANCIA,
        MAX(P.CEPFINAL) KEEP (DENSE_RANK LAST ORDER BY P.DISTANCIA) 
            OVER (PARTITION BY R.CODROTA) AS destino_final
    FROM PCROTAEXP R
    INNER JOIN PCPRACA P ON R.CODROTA = P.ROTA
    WHERE R.CODROTA = NVL(:id, R.CODROTA)
)
SELECT DISTINCT CODROTA,
    '45829110' AS ORIGINPOSTALCODE,
    destino_final AS DESTINYPOSTALCODE,
    LISTAGG(DISTINCT CEPINICIAL, ', ') WITHIN GROUP (ORDER BY DISTANCIA) AS ROUTESTOP_POSTALCODE,
    '1' AS BRANCHCODE, 
    'TRUE' AS ROUNDTRIP, 
    CODROTA AS TRACEIDENTIFIER
FROM dados_completos
WHERE CEPINICIAL != '45829110'      -- Exclui o CEP de origem
  AND CEPINICIAL != destino_final   -- Exclui o CEP de destino
GROUP BY CODROTA, destino_final
