SELECT 
      PCROTAEXP.ROWID
    , PCROTAEXP.CODROTA 
    , PCROTAEXP.CODROTAPRINCIPAL 
    , PCROTAEXP.DESCRICAO 
    , PCROTAEXP.PERCAJUDA 
    , PCROTAEXP.VLAJUDA 
    , PCROTAEXP.DIASENTREGA
    , PCROTAEXP.RASTREADA 
    , PCROTAEXP.TIPOCOMISSAO 
    , PCROTAEXP.PRAZOPREVENT 
    , PCROTAEXP.KMROTA 
    , PCROTAEXP.NUMDIARIA 
    , PCROTAEXP.VLDIARIA 
    , PCROTAEXP.SEQENTREGA 
    , PCROTAEXP.VLMINCARREG 
    , J1.DESCRICAO J1_DESCRICAO
    , PCROTAEXP.PERCOMMOT 
    , PCROTAEXP.PERCOMMOT2 
    , PCROTAEXP.PERCOMMOT3 
    , PCROTAEXP.VALORCOMMOT 
    , PCROTAEXP.DIASEG 
    , PCROTAEXP.DIATER 
    , PCROTAEXP.DIAQUA 
    , PCROTAEXP.DIAQUI 
    , PCROTAEXP.DIASEX 
    , PCROTAEXP.DIASAB 
    , PCROTAEXP.DIADOM 
    , PCROTAEXP.SERIENFETV14 
    , PCROTAEXP.SERIENFESCANTV14 
    , PCROTAEXP.PROXNUMNFETV14 
    , PCROTAEXP.PROXNUMNFESCANTV14 
    , PCROTAEXP.QTENTREGA 
    , PCROTAEXP.PERFRETEVALOR 
    , PCROTAEXP.VLFRETEENTREGA 
    , PCROTAEXP.ALIQICMSFRETE 
    , PCROTAEXP.VLFRETETON 
FROM 
    PCROTAEXP 
    LEFT JOIN PCROTAEXP J1 ON PCROTAEXP.CODROTAPRINCIPAL = J1.CODROTA

WHERE 
    PCROTAEXP.ROWID = NVL(:id, PCROTAEXP.ROWID)
    AND PCROTAEXP.CODROTAPRINCIPAL = NVL(:codrotaprincipal, PCROTAEXP.CODROTAPRINCIPAL)
