/*
    Atualiza os valores de uma faixa de frete (rotina 982 - Cadastro de
    Figura de Frete). Chave composta: CODTRANSPORTE + CODPRACAORIGEM +
    CODPRACADESTINO + CODTIPOVEICULO.
*/

UPDATE PCTRANSPORTEPRACA
SET
      VLINICIO = :VLINICIO
    , VLFINAL  = :VLFINAL
WHERE
    CODTRANSPORTE   = :CODTRANSPORTE
    AND CODPRACAORIGEM  = :CODPRACAORIGEM
    AND CODPRACADESTINO = :CODPRACADESTINO
    AND CODTIPOVEICULO  = :CODTIPOVEICULO
