SELECT 
    -- 1. Métricas Financeiras (Valores)
    ROUND(SUM(CASE WHEN PCMOV.CODOPER = 'S' THEN PCMOV.QT * PCMOV.PUNIT ELSE 0 END), 2) AS VALOR_BRUTO,
    ROUND(SUM(CASE WHEN PCMOV.CODOPER = 'ED' THEN PCMOV.QT * PCMOV.PUNIT ELSE 0 END), 2) AS VALOR_DEVOLUCAO,
    ROUND(
        SUM(CASE WHEN PCMOV.CODOPER = 'S' THEN PCMOV.QT * PCMOV.PUNIT ELSE 0 END) - 
        SUM(CASE WHEN PCMOV.CODOPER = 'ED' THEN PCMOV.QT * PCMOV.PUNIT ELSE 0 END), 
    2) AS VALOR_LIQUIDO,

    -- 2. Métricas Físicas (Quantidades)
    SUM(CASE WHEN PCMOV.CODOPER = 'S' THEN PCMOV.QT ELSE 0 END) AS QT_VENDIDA,
    SUM(CASE WHEN PCMOV.CODOPER = 'ED' THEN PCMOV.QT ELSE 0 END) AS QT_DEVOLVIDA,
    SUM(CASE WHEN PCMOV.CODOPER = 'S' THEN PCMOV.QT ELSE 0 END) - 
    SUM(CASE WHEN PCMOV.CODOPER = 'ED' THEN PCMOV.QT ELSE 0 END) AS QT_LIQUIDA,
    SUM(CASE WHEN PCMOV.CODOPER = 'S' THEN PCMOV.PESOBRUTO ELSE 0 END) AS PESO_BRUTO_S
    -- SUM(CASE WHEN PCMOV.CODOPER = 'ED' THEN PCMOV.PESOBRUTO ELSE 0 END) AS PESO_BRUTO_ED

FROM PCMOV
JOIN PCPRODUT ON (PCPRODUT.CODPROD = PCMOV.CODPROD)
WHERE PCPRODUT.CODFORNEC = 5503
  AND PCMOV.DTMOV BETWEEN TO_DATE('17/05/2026', 'DD/MM/YYYY') AND TO_DATE('13/06/2026', 'DD/MM/YYYY')
  AND PCMOV.CODFILIAL = 2 -- Informar a filial que deseja.
  AND PCMOV.CODOPER IN ('S', 'ED');


SELECT SUM(QT * PUNIT)
FROM PCMOV
JOIN PCPRODUT ON (PCPRODUT.CODPROD = PCMOV.CODPROD)
--JOIN PCFORNEC ON (PCPRODUT.CODFORNEC = PCPRODUT.CODPROD)
WHERE PCPRODUT.CODFORNEC = 5503 
AND PCMOV.DTMOV BETWEEN '13-JUN-2026' AND '14-JUN-2026'
-- AND PCMOV.DTMOV BETWEEN TO_DATE('13-06-2026', 'DD-MM-YYYY') AND TO_DATE('13-06-2026', 'DD-MM-YYYY')
--AND PCMOV.CODOPER NOT IN( 'S','SI','E', 'SM','ST', 'ET','EI','SB')
--AND PCMOV.NUMNOTA = 783669 
AND PCMOV.CODOPER IN ('ED')
AND pcmov.CODFILIAL = 13;
--GROUP BY PCMOV.CODFILIAL, PCMOV.CODOPER,PCMOV.DTMOV;
--------------FILIAL 2 --------------
-- 502.288,86 - VALOR BRUTO VENDA
-- 10.769,00 - QUANTIDADE BRUTA DE VENDAS
-- 25.695,07 - VALOR TOTAL DE DEVOLVIDA
-- 513,98 - QUANTIDADE BRUTA DEVOLVIDA
-- -------------------------------------
-- --------------FILIAL 13 --------------
-- 113.346,84 - VALOR BRUTO VENDA
-- 2.352,00 - QUANTIDADE BRUTA DE VENDAS
-- 3.845,22 - VALOR TOTAL DE DEVOLVIDA
-- 85,70 - QUANTIDADE BRUTA DEVOLVIDA
--------------------------------------