WITH

CTE_VEICULO_BASE AS (
    SELECT 
        ROWID, CODVEICULO, PLACA 
    FROM 
        PCVEICUL 
    WHERE 1=1 
        AND PCVEICUL.ROWID = NVL(:row_id, PCVEICUL.ROWID)
        AND PCVEICUL.CODVEICULO = NVL(:vehicle_id, PCVEICUL.CODVEICULO)
        AND PCVEICUL.PLACA = NVL(:license_plate, PCVEICUL.PLACA)
),

VEICULO AS (
    SELECT
        PCVEICUL.ROWID,
        'Brazil' AS COUNTRY,
        REPLACE(PCVEICUL.PLACA, '-', '') AS LICENSEPLATE,
        CASE
            WHEN PCVEICUL.TIPOVEICULO2 = '0' THEN 'Traction'
            WHEN PCVEICUL.TIPOVEICULO2 = '1' THEN 'Implement'
        END VEHICLECLASSIFICATION,
        CASE
            -- WHEN PCVEICUL.TIPOVEICULO = 'L'         AND PCVEICUL.PESOCARGAKG <= 3500 THEN 'Passenger'
            -- WHEN PCVEICUL.TIPOVEICULO = 'M'         AND PCVEICUL.PESOCARGAKG <= 3500 THEN 'CommercialLightweight'
            -- WHEN PCVEICUL.TIPOVEICULO IN ('P', 'E') AND PCVEICUL.PESOCARGAKG > 3500 THEN 'HeavyCommercial'
            WHEN PCVEICUL.TIPOVEICULO = 'L'         THEN 'Passenger'
            WHEN PCVEICUL.TIPOVEICULO = 'M'         THEN 'CommercialLightweight'
            WHEN PCVEICUL.TIPOVEICULO IN ('P', 'E') THEN 'HeavyCommercial'
        END AS VEHICLECATEGORY,
        CASE
            WHEN PCVEICUL.QTEIXOS = '1' THEN 'Axle01'
            WHEN PCVEICUL.QTEIXOS = '2' THEN 'Axle02'
            WHEN PCVEICUL.QTEIXOS = '3' THEN 'Axle03'
            WHEN PCVEICUL.QTEIXOS = '4' THEN 'Axle04'
            WHEN PCVEICUL.QTEIXOS = '5' THEN 'Axle05'
            WHEN PCVEICUL.QTEIXOS = '6' THEN 'Axle06'
            WHEN PCVEICUL.QTEIXOS = '7' THEN 'Axle07'
            WHEN PCVEICUL.QTEIXOS = '8' THEN 'Axle08'
            WHEN PCVEICUL.QTEIXOS = '9' THEN 'Axle09'
            WHEN PCVEICUL.QTEIXOS = '10' THEN 'Axle10'
        END AS VEHICLEAXLES,
        CASE
            WHEN PCVEICUL.TIPORODADO = '0' THEN 'CityDelivery'
            WHEN PCVEICUL.TIPORODADO = '1' THEN 'Truck'
            WHEN PCVEICUL.TIPORODADO = '2' THEN 'Toco'
            WHEN PCVEICUL.TIPORODADO = '3' THEN 'Toco'
            WHEN PCVEICUL.TIPORODADO = '4' THEN 'VAN'
            WHEN PCVEICUL.TIPORODADO = '5' THEN 'Utility'
            WHEN PCVEICUL.TIPORODADO = '6' THEN 'VUC'
        END AS TYPE, -- Type = ['CityDelivery', 'Toco', 'Truck', 'Utility', 'VAN', 'VUC'],
        PCLOCALIZACAO.DESCRICAO AS VEHICLE_LOCALIZATION_DESCRIPTION,
        'Brazil' AS VEHICLEOWNER_COUNTRY,
        REPLACE(REPLACE(REPLACE(PCVEICUL.CGCCPFPROPRIETARIO, '-', ''), '.', ''), '/', '') AS VEHICLEOWNER_NATIONALID,
        REPLACE(REPLACE(REPLACE(PCFORNEC.CGC, '-', ''), '.', ''), '/', '') AS HIRED_NATIONALID,
        LPAD(PCVEICUL.CODIGORNTRC, 9, '0') AS RNTRC,
        REPLACE(PCFORNEC.FANTASIA, '.', ' ') AS NOMEFANTASIA,
        CASE
            WHEN PCFORNEC.TIPOPESSOA = 'F' THEN 'Person'
            WHEN  PCFORNEC.TIPOPESSOA = 'J' THEN 'Company'
            ELSE ''
        END AS VEHICLEOWNER_TYPE,
        PCVEICUL.NOMEPROPRIETARIO AS VEHICLEOWNER_VEHICLEPERSONALINFORMATION_NAME
    FROM
        PCVEICUL
        LEFT JOIN PCFORNEC ON PCFORNEC.CODFORNEC = PCVEICUL.CODFORNEC
        LEFT JOIN PCLOCALIZACAO ON PCVEICUL.CODLOCALIZACAO = PCLOCALIZACAO.CODIGO
        INNER JOIN CTE_VEICULO_BASE ON PCVEICUL.CODVEICULO = CTE_VEICULO_BASE.CODVEICULO
)

SELECT 
    JSON_OBJECT(
        'Country' VALUE VEICULO.COUNTRY,
        'LicensePlate' VALUE VEICULO.LICENSEPLATE,
        'VehicleClassification' VALUE VEICULO.VEHICLECLASSIFICATION,
        'VehicleCategory' VALUE VEICULO.VEHICLECATEGORY,
        'VehicleAxles' VALUE VEICULO.VEHICLEAXLES,
        'Type' VALUE VEICULO.TYPE,
        'VehicleOwner' VALUE JSON_OBJECT(
            'Country' VALUE VEICULO.VEHICLEOWNER_COUNTRY,
            'NationalId' VALUE CASE VEHICLEOWNER_TYPE WHEN 'F' THEN VEICULO.VEHICLEOWNER_NATIONALID ELSE VEICULO.HIRED_NATIONALID END,
            'BrazilianSettings' VALUE JSON_OBJECT(
                'RNTRC' VALUE VEICULO.RNTRC,
                'VehiclePessoaJuridica' VALUE JSON_OBJECT(
                    'NomeFantasia' VALUE VEICULO.NOMEFANTASIA
                )
            ),
            'Type' VALUE VEICULO.VEHICLEOWNER_TYPE,
            'VehiclePersonalInformation' VALUE JSON_OBJECT(
                'Name' VALUE VEICULO.VEHICLEOWNER_VEHICLEPERSONALINFORMATION_NAME
            )
        )
    ) AS JSON_DOCUMENT
FROM VEICULO